Upgrade alpine to 3.14 for latest versions
influxdata/influxdata-docker pull request #524
Opened 2021-08-29 10:22 UTC by orgads

2021-08-29 14:56 UTC, orgads commented
@wbaker85 @codyshepherd

2021-08-29 14:58 UTC, orgads commented
The current images have a critical vulnerability in apk-tools: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-36159

It is possible to just rebuild the images, but this can be a good opportunity to upgrade.

2021-08-30 15:27 UTC, codyshepherd requested changes
This is helpful, thank you. 

However, as this is a security issue, we should update all the Alpine-based images. If you have the time, please the Alpine version everywhere; otherwise I'm happy to do it.

The files in question should be the output of the following bash commands from a fresh checkout of this repo:

```bash
files=$(find . -name Dockerfile -print)
for f in $files; do [[ $(grep -cri alpine $f) == 1 ]] && echo $f; done
```

2021-08-30 15:30 UTC, orgads commented
Done, but the previous attempt #498 had some build failures. Let's see how it goes...

2021-08-30 15:49 UTC, codyshepherd approved these changes

2021-08-30 15:49 UTC, merged

2021-08-30 15:50 UTC, orgads commented
Thanks! When can I expect the new images on docker hub?

2021-08-30 17:52 UTC, codyshepherd commented
@orgads The timeline will vary depending on product. I'm checking on this, but I think we will probably wait until the next release to release the version bump to official images for influxdb, chronograf, and kapacitor. Telegraf will definitely not be updated until next release.

I believe new releases for influxdb 1.8, 1.9 and 2.0 are upcoming in September.

2021-08-30 18:00 UTC, orgads commented
Thank you.